"""
app.py
------
A premium Streamlit demo for the Weak Supervision Labeling Factory.
"""

import joblib
import pandas as pd
import streamlit as st
from pathlib import Path

MODEL_PATH = Path(__file__).resolve().parent / "models" / "text_classifier.joblib"
DATA_PATH = Path(__file__).resolve().parent / "data" / "labeled_reviews.parquet"

st.set_page_config(page_title="Data Labeling Factory", page_icon="🏭", layout="wide")

# Custom CSS for premium look
st.markdown("""
<style>
    .reportview-container {
        background: #fafafa;
    }
    .big-font {
        font-size:300% !important;
        font-weight: 700;
        color: #1e3a8a;
    }
    .metric-card {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        text-align: center;
        margin-bottom: 20px;
    }
    .metric-value {
        font-size: 2.5rem;
        font-weight: bold;
        color: #2563eb;
    }
    .metric-label {
        font-size: 1rem;
        color: #64748b;
        text-transform: uppercase;
        letter-spacing: 1px;
    }
</style>
""", unsafe_allow_html=True)

st.markdown('<p class="big-font">🏭 Enterprise Data Labeling Factory</p>', unsafe_allow_html=True)
st.markdown(
    "**A demonstration of Data-Centric AI.** This classifier was trained entirely on "
    "programmatic labels generated by Snorkel's LabelModel from heuristic rules and regex patterns "
    "— **zero hand-labeled training data was used.**"
)

if not MODEL_PATH.exists():
    st.error("⚠️ No trained model found. Run `python main.py` first to build the pipeline, then relaunch this app.")
    st.stop()

pipeline = joblib.load(MODEL_PATH)

# Display some high-level metrics if data exists
if DATA_PATH.exists():
    df = pd.read_parquet(DATA_PATH)
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown(f'<div class="metric-card"><div class="metric-value">{len(df):,}</div><div class="metric-label">Auto-Labeled Rows</div></div>', unsafe_allow_html=True)
    with col2:
        st.markdown(f'<div class="metric-card"><div class="metric-value">{len(df["weak_label_name"].unique())}</div><div class="metric-label">Categories</div></div>', unsafe_allow_html=True)
    with col3:
        st.markdown(f'<div class="metric-card"><div class="metric-value">0</div><div class="metric-label">Manual Hours Spent</div></div>', unsafe_allow_html=True)

st.write("---")

col_input, col_results = st.columns([1, 1])

with col_input:
    st.subheader("Test the Classifier")
    text = st.text_area(
        "Paste a customer review, app store comment, or support ticket:",
        placeholder="The app keeps crashing every time I try to upload a photo...",
        height=150,
    )
    
    analyze_btn = st.button("🚀 Analyze Text", type="primary", use_container_width=True)

with col_results:
    if analyze_btn and text.strip():
        pred = pipeline.predict([text])[0]
        proba = pipeline.predict_proba([text])[0]
        classes = pipeline.classes_
        
        st.subheader("Analysis Results")
        st.success(f"**Predicted Category:** `{pred}`")
        
        # Create a nice dataframe for the bar chart
        prob_df = pd.DataFrame({"Category": classes, "Confidence": proba})
        prob_df = prob_df.set_index("Category").sort_values("Confidence", ascending=True)
        st.bar_chart(prob_df)
    elif analyze_btn:
        st.warning("Please enter some text to analyze.")
    else:
        st.info("👈 Enter text and click Analyze to see the model in action.")

st.write("---")
with st.expander("🔍 How this pipeline works (Under the Hood)"):
    st.markdown(
        """
        ### The Weak Supervision Paradigm
        
        1. **Write Labeling Functions (LFs):** Instead of manually labeling rows, we write simple Python functions (heuristics, keyword matches, regex, small models) that vote on a category or abstain.
        2. **Train a Generative Model (Snorkel LabelModel):** The LFs are noisy and conflict with each other. Snorkel uses matrix completion to mathematically estimate the true accuracy and correlation of each LF *without needing any ground truth*.
        3. **Generate Probabilistic Labels:** The LabelModel fuses the noisy LF votes into clean, probabilistic labels for the entire dataset.
        4. **Train Downstream Classifier:** A standard machine learning model (like TF-IDF + Logistic Regression or a Transformer) is trained on these probabilistic labels, generalizing beyond the rules you wrote.
        """
    )
